### ISSUE TITLE
export 'OidcProvider' (imported as 'OidcProvider') was not found in '@axa-fr/react-oidc/dist/index' (module has no exports)

### ISSUE THREAD

**Issue by reeaazz** [AxaFrance/react-oidc#1006]
### Issue and Steps to Reproduce

I tried to recreate this simple app but when i try to call few things from the module i get lots of errors (module has no exports) 

#### Actual
ERROR in ./src/App.js 20:30-42
export 'OidcProvider' (imported as 'OidcProvider') was not found in '@axa-fr/react-oidc/dist/index' (module has no exports)

ERROR in ./src/Layout/Header.jsx 13:6-17
export 'useOidcUser' (imported as 'useOidcUser') was not found in '@axa-fr/react-oidc' (module has no exports)

ERROR in ./src/Layout/Header.jsx 62:10-21
export 'useOidcUser' (imported as 'useOidcUser') was not found in '@axa-fr/react-oidc' (module has no exports)

ERROR in ./src/pages/Admin.jsx 9:30-40
export 'OidcSecure' (imported as 'OidcSecure') was not found in '@axa-fr/react-oidc' (module has no exports)

ERROR in ./src/pages/Home.jsx 15:6-13
export 'useOidc' (imported as 'useOidc') was not found in '@axa-fr/react-oidc' (module has no exports)

ERROR in ./src/pages/Home.jsx 19:6-20
export 'useOidcIdToken' (imported as 'useOidcIdToken') was not found in '@axa-fr/react-oidc' (module has no exports)

ERROR in ./src/pages/Home.jsx 43:10-17
export 'useOidc' (imported as 'useOidc') was not found in '@axa-fr/react-oidc' (module has no exports)

ERROR in ./src/pages/Home.jsx 43:19-33
export 'useOidcIdToken' (imported as 'useOidcIdToken') was not found in '@axa-fr/react-oidc' (module has no exports)

ERROR in ./node_modules/@axa-fr/react-oidc/dist/index.js 1:0-59
Module not found: Error: Can't resolve './FetchToken' in '/Users/amarrai/react-oidc-example-main/node_modules/@axa-fr/react-oidc/dist'
Did you mean 'FetchToken.js'?
BREAKING CHANGE: The request './FetchToken' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@axa-fr/react-oidc/dist/index.js 2:0-46
Module not found: Error: Can't resolve './OidcProvider' in '/Users/amarrai/react-oidc-example-main/node_modules/@axa-fr/react-oidc/dist'
Did you mean 'OidcProvider.js'?
BREAKING CHANGE: The request './OidcProvider' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@axa-fr/react-oidc/dist/index.js 3:0-58
Module not found: Error: Can't resolve './OidcSecure' in '/Users/amarrai/react-oidc-example-main/node_modules/@axa-fr/react-oidc/dist'
Did you mean 'OidcSecure.js'?
BREAKING CHANGE: The request './OidcSecure' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@axa-fr/react-oidc/dist/index.js 4:0-74
Module not found: Error: Can't resolve './ReactOidc' in '/Users/amarrai/react-oidc-example-main/node_modules/@axa-fr/react-oidc/dist'
Did you mean 'ReactOidc.js'?
BREAKING CHANGE: The request './ReactOidc' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@axa-fr/react-oidc/dist/index.js 5:0-53
Module not found: Error: Can't resolve './User' in '/Users/amarrai/react-oidc-example-main/node_modules/@axa-fr/react-oidc/dist'
Did you mean 'User.js'?
BREAKING CHANGE: The request './User' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@axa-fr/react-oidc/dist/index.js 6:0-55
Module not found: Error: Can't resolve './vanilla/parseTokens' in '/Users/amarrai/react-oidc-example-main/node_modules/@axa-fr/react-oidc/dist'
Did you mean 'parseTokens.js'?
BREAKING CHANGE: The request './vanilla/parseTokens' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 14 errors
### Additional Details

- Installed packages:

**Comment by jcrawl3y** [comment]
We're getting the same issue after updating to the latest version...

**Comment by DGanichev** [comment]
We also had this issue with the latest version of the library yesterday. So we downgraded to a previous working version (in our case 6.10.21) and removed the ^ sign in front of the verion in the package.json, and now it all works again.

**Comment by jafin** [comment]
Ugh, may be related to a PR I did. Can I confirm which version didn't work, and which one did @reeaazz .   I'll investigate now and try to offer a fix.

**Comment by reeaazz** [comment]
The latest version did not work @jafin. The one mentioned by @DGanichev  6.10.21 without ^ one worked fine.

**Comment by guillaume-chervet** [comment]
Thank to @jafin it should work not with the latest version.

**Comment by jafin** [comment]
To whomever had error compiling/running the package/react demo app, could you please try https://github.com/jafin/react-oidc/tree/fix/react-app-es-imports  and let me know if it works from that branch? 
I've raised a PR but would be great is someone can validate it.

**Comment by guillaume-chervet** [comment]
It should be ok now with version 6.16.8 @reeaazz

**Comment by guillaume-chervet** [comment]
Hi @jafin @reeaazz , is shoulb be OK now. May we close the issue ?

**Comment by jafin** [comment]
@guillaume-chervet I haven't updated to later versions of lib (busy on another thing) but sounds like you resolved it, fine with me to close 👍🏻

**Comment by guillaume-chervet** [comment]
Hi @reeaazz , thank you for your issue. I think it is resolved. I close the issue but feel free to reopen it if you need.
