### ISSUE TITLE
Service Worker Not Supported on IIS

### ISSUE THREAD

**Issue by bkershaw** [AxaFrance/react-oidc#1019]
### Issue and Steps to Reproduce

I have a react app that uses the react-oidc library and works excellently on localhost.  I deployed it to a windows server hosted via IIS.  

If I assign a CName DNS binding for the application, the service worker never installs, and I receive the default error for ServiceWorkerNotSupported.  (I have tried to add the dns name to the trusted domains and this did not solve the issue).

However, if I add a binding for a localhost port such as 4444 and browse the website, the service worker installs it, and everyone is happy.  

Am I missing a configuration step to assign a dns name ?

### Versions
6.14.9

### Screenshots
![image](https://user-images.githubusercontent.com/34863242/228230984-fea4991b-3fc1-402d-b808-75bdb7bca30a.png)

**Comment by guillaume-chervet** [comment]
Hi @bkershaw , thank you very much for your issue and very sorry for the delay.
I know very well IIS.
I do not know how is your configuration so it.will be hard to help. You just need to map service worker as a static content like your html and the others javascript. Service worker is a javascript file like others for your server.

**Comment by bkershaw** [comment]
@guillaume-chervet the react app is in wwwroot directory and has an application pool and website with bindings.  I had to create a web.config file with rewrites so the routing between paths worked properly.  

How else could I map static content such as service worker?  I think it's so odd that when I expose a port such as 1234 in the bindings and browse that local host port the service worker installs no problem, but with a DNS alias in the bindings it does not install service worker.  Thank you for help 😁

**Comment by bkershaw** [comment]
I'm sorry this issue was a result of not using HTTPS cert thank you for the help!

**Comment by guillaume-chervet** [comment]
Thank you @bkershaw for your feeback :)
Have fun!
