### ISSUE TITLE
`useOidcFetch` as a `useEffect` dependency

### ISSUE THREAD

**Issue by jasonaowen** [AxaFrance/react-oidc#1023]
### Issue and Steps to Reproduce

I want to use the `fetch` returned by the `useOidcFetch` hook in a [`useEffect`](https://react.dev/reference/react/useEffect) setup function. My linter warns me that I ought to list `fetch` as one of the dependencies of the effect: 

> React Hook `useEffect` has a missing dependency: `'fetch'`. Either include it or remove the dependency array  `react-hooks/exhaustive-deps`

However, it seems the value returned by `useOidcFetch` differs from call to call, so listing `fetch` in the dependencies array of  `useEffect` causes the effect to run in an infinite loop - meaning the same call to `fetch` is made over and over, wasting network resources.

For now, I am omitting `fetch` from the dependency array, and ignoring the linter error, but it would be nice if this would work out of the box.

```ts
import React, { useEffect, useState } from 'react';
import { useOidcFetch } from '@axa-fr/react-oidc';

// Mount this component inside <OidcProvider> and <OidcSecure>
export const Example = () => {
  const { fetch } = useOidcFetch();
  const [reponse, setResponse] = useState(null as any);
  useEffect(() => {
    fetch('https://api.example.com') // set this to a URL configured to allow CORS requests
      .then(setResponse)
      .then(() => console.log(`Fetch finished at ${Date()}`))
      .catch(console.error);
  }, [fetch, setResponse]); // remove fetch to prevent repeated requests, but then ESLint warns about react-hooks/exhaustive-deps
  return <div>See console log</div>;
};
```

### Versions

`@axa-fr/react-oidc` 6.16.10

#### Expected

The effect should only be run once.

#### Actual

The effect is run repeatedly, so long as `fetch` is in the dependency array.

**Comment by guillaume-chervet** [comment]
Hi @jasonaowen , thank you for your issue. It is a good and simple enhanczmznt to add.

**Comment by guillaume-chervet** [comment]
Hi @jasonaowen , I close the issue, thank you for it, feel free to reopen it if needed.
