### ISSUE TITLE
Potentially unexpected behavior with useOidcFetch - un-auth'd calls are delayed

### ISSUE THREAD

**Issue by jsnowfreedman** [AxaFrance/react-oidc#1026]
### Issue and Steps to Reproduce

I'll be honest, I am not 100% if this is an issue, or a design decision and I'm just having a PEBCAK moment.

I am using this package with React, and I have an OIDC provider wrapped much like in the examples.
My very next component within the provider is getting the fetch of this library:
```js 
const {fetch} = useOidcFetch();
```

I am then immediately making a fetch request to one of my APIs. This endpoint does not care if I am authenticated or not, however can/will return slightly different data if I am.

I noticed that when I am logged in, or have silent login enabled, my page - and therefor the request, loads instantly, and since this is on my machine, the data is returned and the page renders immediately.
What caught me a bit off guard is that if I am _not_ logged in, but I do not force logging in for that component, the fetch was delayed by about 10 seconds.

I've traced it down to these highlights:
- In FetchToken.tsx, the `useOidcFetch` (which is what I am grabbing in order to make stated API call), is then calling `fetchWithToken`
- In `fetchWithToken` there is a line then goes `... await oidc.getValidTokenAsync();`
- Jumping through a proxy method, soon we end up hitting the [getValidTokensAsync](https://github.com/AxaFrance/react-oidc/blob/9b791fa219a0795abb6b52515453428bd6562d51/packages/react/src/oidc/vanilla/parseTokens.ts#L148-L153) function
- What is interesting about this is that it is trying to check if the token is valid, with a while loop & sleep, wherein it sleeps for 100ms, and tries 50 times. This leads to the 10 second delay I am seeing

As a sanity check, I printed the timestamp, taken before and after calling the `getValidTokenAsync` call:
```
In FetchWithToken 2  ...748437 
In FetchWithToken 3  ...758831
```
After modifying the default parameter to 5 tries (which, times 20ms, is a more UX friendly 1 second, but still longer than I would like):
```
In FetchWithToken 2  ...913396
In FetchWithToken 3  ...914431
```

---
I am asking here for clarification on three parts:
1) Why is this loop occurring? From what I can tell its just looping a check to see if the token has expired yet [isTokensValid](https://github.com/AxaFrance/react-oidc/blob/9b791fa219a0795abb6b52515453428bd6562d51/packages/react/src/oidc/vanilla/parseTokens.ts#L131-L136).
    1) Is this because in the background the token could be getting fetched?
2) I do not see any way to override this timeout or test count. The method technically takes the parameter, but fetch doesn't seem to use it or proxy parameters in.
3) Is this occurring because I am making an assumption about how/when I can/should be using the `with/useOidcFetch`

It feels like either the loop isn't needed at all, or when building a fetcher, I should be able to pass in options to override the default behavior.

In the meantime, to bypass this, I made a custom `fetchWithToken` that does inject the timeout/try parameter to the `getValidTokenAsync` call.

If there is a preferred solution to this, I am happy to make a PR for any changes.

### Versions
6.16.12

#### Actual
A bit hard to show time delays in a picture, I can upload a video if needed later.

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @jsnowfreedman ,

Thank you for your issue very well described.
This fetch is built for adding auth token in HTTP headers.
Temporary you may use default fetch when your are not authenticated.

It is a quick and easy feature to add.

https://github.com/AxaFrance/react-oidc/blob/9b791fa219a0795abb6b52515453428bd6562d51/packages/react/src/oidc/FetchToken.tsx#L25

When Token not authenticated, just send request whithout token.
