### ISSUE TITLE
Force update of user data

### ISSUE THREAD

**Issue by erritis** [AxaFrance/react-oidc#1027]
### Issue

I can't figure out how to force update user data.

#### Expected

The presence of a method to force a call to update user data (refresh) in useOidcUser:
const { oidcUser, oidcUserLoadingState, refresh } = useOidcUser();

#### Actual

There is no such method. I could not find an alternative in the code.

**Comment by guillaume-chervet** [comment]
Hi @erritis ,
Thank you for your issue.
It is a good ansd simple enhancement to add.

**Comment by zyofeng** [comment]
Is it just a matter of replicating the call to user info endpoint and refresh the state? I can possibly take a stab at it this week.

**Comment by erritis** [comment]
In general, it would be possible to wrap the receipt of the user in a provider, which is built into the main oidc provider. The benefits of data in context cannot be overestimated.
But since there can be several authorization providers here, and getting a user is used with a generic, which may differ for the same authorization provider, this will most likely require significant revisions.

**Comment by guillaume-chervet** [comment]
hi @erritis ,

very sorry for the delay :I have code it like this https://github.com/AxaFrance/react-oidc/pull/1076 it seem to work !

**Comment by guillaume-chervet** [comment]
Hi @erritis, Thank you for your issue. I close it but feel free to reopen it if your need.
