### ISSUE TITLE
On app start using Google Auth and Auth0: Uncaught TypeError: Cannot read properties of undefined (reading 'silent_login_uri')

### ISSUE THREAD

**Issue by danorlando** [AxaFrance/react-oidc#1032]
### Issue and Steps to Reproduce
I'm hoping someone can help with this as I"ve been stuck on this issue for quite a while. I followed the exact setup instructions from the readme, but when I start the app I immediately get the error:
Uncaught TypeError: Cannot read properties of undefined (reading 'silent_login_uri')
 
I have tried this with both Google auth and Auth0 with the following configurations passed to the OidcProvider:
```
export const configurationAuth0 = {
  client_id: import.meta.env.VITE_AUTH0_CLIENT_ID,
  redirect_uri: window.location.origin + '/callback',
  scope: 'openid profile email api offline_access',
  authority: import.meta.env.VITE_AUTH0_AUTHORITY,
  refresh_time_before_tokens_expiration_in_second: 86400,
  service_worker_relative_url: '/OidcServiceWorker.js',
  service_worker_only: false,
};

export const configurationGoogle = {
  client_id: import.meta.env.VITE_GOOGLE_OIDC_CLIENT_ID,
  redirect_uri: `${window.location.origin}/multi-auth/callback-google`,
  silent_redirect_uri: window.location.origin + '/multi-auth/silent-callback-google',
  // silent_login_uri: window.location.origin + '/authentication/silent-login',
  scope: 'openid profile email',
  authority: 'https://accounts.google.com/',
  service_worker_relative_url: '/OidcServiceWorker.js',
  service_worker_only: false,
  token_request_extras: {
      client_secret: import.meta.env.VITE_GOOGLE_OIDC_CLIENT_SECRET,
  },
  monitor_session: false,
};
```

You can see that I tried adding in silent_login_uri, even though it is not required, but it is still undefined. The error occurs on line 84 of oidc.ts:
```
let silent_login_uri = configuration.silent_login_uri;
```

This is with the latest version of @axa-fr/react-oidc. 

I thought I followed the directions pretty well. Did I miss a step?

[Link to branch in repo where this can be verified](https://github.com/danorlando/chatgpt-clone/tree/feat-oidc-auth-with-axafrance-react-oidc)

Files with related code:
[App.jsx](https://github.com/danorlando/chatgpt-clone/blob/feat-oidc-auth-with-axafrance-react-oidc/client/src/App.jsx): Where provider is located
[root.jsx](https://github.com/danorlando/chatgpt-clone/blob/feat-oidc-auth-with-axafrance-react-oidc/client/src/routes/Root.jsx): checks if !isAuthenticated and displays login button
[OidcTrustedDomains.js](https://github.com/danorlando/chatgpt-clone/blob/feat-oidc-auth-with-axafrance-react-oidc/client/public/OidcTrustedDomains.js)
[configs.js](https://github.com/danorlando/chatgpt-clone/blob/feat-oidc-auth-with-axafrance-react-oidc/client/src/auth/configs.js): Where the configs are

Thanks!

**Comment by guillaume-chervet** [comment]
Hi @danorlando thank you for your issue. Your application look fun.
I am not sure but by lookin the code i think that your may use 
<OidcProvider configuration={configurationAuth0}>
Instead of
<OidcProvider {...configurationAuth0}>

**Comment by danorlando** [comment]
Hi @guillaume-chervet, 
Wow, I can't believe I missed that! 
Thank you so much for the prompt reply. I knew it had to be something really stupid.  

Thanks again for having a look.

**Comment by danorlando** [comment]
Hey @guillaume-chervet, 
Sorry to bother again, but after I made that change, it worked once with Auth0 time, where it pulled up the Auth0 login successfully. I then changed it to use the google configuration, and it complained with about the redirect_uri which I had set to a non-existant route, which was a good sign. I fixed the redirect_uri, and started getting a 400 on the token endpoint because the code is undefined. I then switched it back to Auth0, and found it to be doing the same thing now.  Do you have any idea why the code might not be getting included when it calls the /token endpoints? 

<img width="868" alt="Screenshot 2023-04-15 at 2 41 05 PM" src="https://user-images.githubusercontent.com/111239/232254655-ddd6d483-86b0-4140-b553-707c24196555.png">

**Comment by danorlando** [comment]
Actually, disregard that. It looks like the issue was because I was just using window.location.origin as the redirect_uri. Not really sure how that is related, but it seems to be working as long as the redirect_uri is set to the window.location.origin + '/authentication/callback'.
