### ISSUE TITLE
Application hangs on callback using Auth0 config and Google auth

### ISSUE THREAD

**Issue by danorlando** [AxaFrance/react-oidc#1033]
First, I just want to say that you guys have done such great work with this library and I'm really hoping to use it for our app because of the flexibility it gives in being able to support any auth provider. However, I'm stuck on an issue that I can't for the life of me figure out and I'm really hoping you can provide some insight into what is going on. 

I have the app configured for auth0, but the same thing happens for google auth. The problem seems specific to this library because I was able to complete the login flow using the react-auth0 library. I've recorded [a video demonstration here](https://www.loom.com/share/d304b5f1a1ab43b7a09d809be29a3e23) to show what is happening and the code can be found [on this branch](https://github.com/danorlando/chatgpt-clone/tree/feat-oidc-auth-with-axafrance-react-oidc), where I have commented out all non-auth related code (see: [App.jsx](https://github.com/danorlando/chatgpt-clone/blob/feat-oidc-auth-with-axafrance-react-oidc/client/src/App.jsx)) and simply plugged in code from the demo app for troubleshooting purposes. The auth0 config I'm using can be found [here](https://github.com/danorlando/chatgpt-clone/blob/feat-oidc-auth-with-axafrance-react-oidc/client/src/auth/configs.js).

After logging in with the identity provider, the app gets stuck on the /authentication/callback route and gets a 404 when trying to load the javascript bundles after it returns back to localhost. I've never seen anything like this before, and I'm really  hoping you might have some insight into what is happening based on your extensive experience with this library.

Thanks so much for your help!

**Comment by guillaume-chervet** [comment]
Hi @danorlando , thank you very much for your message.
Thank you for also for the video.
The error is not link to react oidc. It seems that javascript files are not found. 
I respond from my mobile so i cannot check the good answer, I remember 
you may add think like 
<base href="/"/> in you html header. And may be add ./ to your script urls.

You can also use # callback if your oidc provider support it. You won't have any script urls issues with # callbacks.

**Comment by danorlando** [comment]
Hi @guillaume-chervet, forgive my ignorance, but can you explain what you mean by # callbacks?

Thanks!

**Comment by guillaume-chervet** [comment]
Configuration with hash route does not require html5 routing.
https://github.com/AxaFrance/react-oidc/blob/39d8d48c3f7c338760dd489885e8bd411e4eba13/packages/react/src/configurations.ts#L38

It can be easier to manage for some scenario. Thank you @danorlando for your feedback 😀

**Comment by danorlando** [comment]
Ok got it, thanks. If I might ask one more question - I noticed that after logging in, it is refetching the token every couple seconds. Is this normal behavior?

**Comment by danorlando** [comment]
@guillaume-chervet I noticed this happens in the demo app as well. Is there a way to prevent this behavior of making a token request every couple seconds?

**Comment by guillaume-chervet** [comment]
Hi @danorlando ,
Just remove refresh_time_before_tokens_expiration_in_second: 86400
From your configuration. It tells the tokens to refresh quasi immediatly :)

I set these parameters just for the demo to  refresh quickly to test.

**Comment by danorlando** [comment]
Ah. wonderful. Thank you!!!

**Comment by danorlando** [comment]
Hi @guillaume-chervet, sorry to keep bothering you, but I removed that line like you said, and it is still refreshing the token every couple seconds. This is my current config:
```
export const configurationAuth0 = {
  client_id: import.meta.env.VITE_AUTH0_CLIENT_ID,
  redirect_uri: window.location.origin + '/authentication/callback',
  silent_redirect_uri: window.location.origin + '/authentication/silent-callback',
  scope: 'openid profile email api offline_access',
  authority: import.meta.env.VITE_AUTH0_AUTHORITY,
  service_worker_relative_url: '/OidcServiceWorker.js',
  service_worker_only: false,
};
```
Any idea what might be causing this?

**Comment by guillaume-chervet** [comment]
Hi @danorlando , 
I am not sure but i think you openid token has wrong or very short expiration date.

May you test to add:
"token_renew_mode": "access_token_invalid"

In you configuration

**Comment by danorlando** [comment]
Hi @guillaume-chervet,
So, I added this to the config object:
`token_renew_mode: TokenRenewMode.access_token_invalid`

I'll share a couple of screenshots that should be helpful in troubleshooting...
First one is the auth0 application configuration for expiration:
![Screenshot 2023-04-18 at 7 25 32 AM](https://user-images.githubusercontent.com/111239/232810216-74dd3d44-1c73-45c6-a81e-94cfdd5ea7d5.png)

Here are the responses from the two different POST requests that are made to the auth0 domain/oauth/token endpoint...

First request:

![Screenshot 2023-04-18 at 7 26 24 AM](https://user-images.githubusercontent.com/111239/232811543-e65f99ab-d6cb-4b85-90e0-df67ffb7672c.png)

Second request to get access token:

![Screenshot 2023-04-18 at 7 26 54 AM](https://user-images.githubusercontent.com/111239/232811650-58af8d4a-a181-4652-b273-8705abda2e79.png)

One thing that I thought was interesting, and I'm not sure if this has anything to do with the issue, but I am a bit concerned about, is that when I pasted the access token into the jwt.io debugger, it says "Invalid Signature": 

![Screenshot 2023-04-18 at 7 40 02 AM](https://user-images.githubusercontent.com/111239/232812474-6ff0c9b6-964b-4a1a-aa10-64f7e2032a07.png)

**Comment by guillaume-chervet** [comment]
Hi @danorlando ,

Thank you for all your rich information.
Yes may you create a new issue ?
I'am in holiday until may without computer so i cannot make some test.
The tokens informations looks fine.
May your copy paste a full access token in you new issue?

**Comment by danorlando** [comment]
@guillaume-chervet 
No problem at all. I generally try to provide as much information as possible. I know from experience that its very hard to identify the source of a problem when not enough information is given ;)

Anyway, I opened a new issue for it. Hopefully we can figure it out and get it resolved quickly because I really like what you have done with this awesome library and I would like to be using it in production.

Thanks again for all your help with this!
