### ISSUE TITLE
Add possibility to adjust token revocation behaviour

### ISSUE THREAD

**Issue by krzempekk** [AxaFrance/react-oidc#1037]
### Issue and Steps to Reproduce

Currently, if `revocationEndpoint` is present in OIDC server configuration, requests are created to revoke both access and refresh token ([code](https://github.com/AxaFrance/react-oidc/blob/master/packages/react/src/oidc/vanilla/logout.ts#L41-L56
)). This behaviour is problematic when using some IdPs, for example AWS Cognito - as their revoke endpoint accepts only refresh token and revokes all access tokens issued to it (see [docs](https://docs.aws.amazon.com/cognito/latest/developerguide/revocation-endpoint.html)). Therefore, one of the revocation requests will always fail and produce unnecessary error on console, which cannot be silenced from outside. 

### Versions

6.16.7

### Screenshots

![image](https://user-images.githubusercontent.com/44374710/233062519-f3333ee3-d6f9-4cb4-a737-bfdc82091b1a.png)

#### Expected

There is option (for example in `OidcConfiguration`) to skip revocation of given token - could be array with token names or just boolean flags.

#### Actual

No such option, one request always fails when using some providers (for example AWS Cognito).

**Comment by guillaume-chervet** [comment]
Hi @krzempekk , thank you very much for your issue.
It is a very nice and simple enhancemet to add.

**Comment by guillaume-chervet** [comment]
Hi @krzempekk , this feature is already working. May we close the issue?

**Comment by krzempekk** [comment]
Hi @guillaume-chervet! Sorry for the delay, feel free to close it.

**Comment by guillaume-chervet** [comment]
thank you @krzempekk
