### ISSUE TITLE
Access tokens in service worker mode

### ISSUE THREAD

**Issue by krzempekk** [AxaFrance/react-oidc#1038]
### Issue and Steps to Reproduce

When using service worker, tokens are not accessible to client code. This is great from security perspective, but we have some use cases in which we need to have access to tokens and still want to utilise service workers (to take advantage of tokens synchronisation between tabs, etc.):
- micro frontends rendered inside and iframe, which rely on parent app for authentication and use its tokens for requests
- internal tools that need to display access token in dev environments.

Configuration option to turn off tokens hiding would be great for us and tokens would still be hidden by service worker by default.

### Versions

6.16.14

#### Expected

There is boolean configuration option (in `OidcConfiguration`, could be named `service_worker_hide_tokens`, `true` by default) to turn off hiding tokens by service worker.

#### Actual

Tokens are always hidden when using service workers.

**Comment by guillaume-chervet** [comment]
Hi @krzempekk, thank you for your issue.

you can disable service worker mode in development just by not configuring the serviceworker file in development you will have the behavior you need.

**Comment by krzempekk** [comment]
Hi @guillaume-chervet!
Thank you for response. Yes, I understand that service worker can be not configured for this behaviour, but in our case we need to use service worker (to have token synchronisation, synchronised renewal, etc.) and still have access to tokens.
As I have said, we have production use cases for that, so it's not only development.

**Comment by guillaume-chervet** [comment]
Hi @krzempekk , I am not sure but does localStorage mode do the job you need? It is the same behavior than Service worker (except you need to inject accessToken manually in each fetch) and you have access token not offuscated.

**Comment by krzempekk** [comment]
Hi @guillaume-chervet! 
Unfortunately localStorage is not an option for us - we have requirement to store tokens only in-memory, as service worker does.

**Comment by guillaume-chervet** [comment]
Thank you @krzempekk , i think i understand your need.
This is possible to add, but the configuration will able to be set from trusteddomains.js for security readon.

**Comment by krzempekk** [comment]
That would be perfectly fine for us to set this configuration from `OidcTrustedDomains.js`. Thank you @guillaume-chervet, looking forward to this :)

**Comment by darkowic** [comment]
@guillaume-chervet just to be clear: in case we decide to use this library (which will probably happen), we will be willing to help resolve the issues we are raising :) I hope you are open to collaboration and enhancements propositions like this one :)

**Comment by guillaume-chervet** [comment]
Hi @darkowic thank you for your message.

How much time do you have?
I am in holiday until 2 of may.

I have many nice issues and enhancements to resolve :)

I will start by blocking issue like yours.

**Comment by darkowic** [comment]
No rush here ;) we are still evaluating this and checking options and limitations. Probably in month we will be working on productizing this.

**Comment by HSULGIT** [comment]
Hi @guillaume-chervet we also need to pass the access token, because of roles that are only provided via access token and not via id token.

**Comment by guillaume-chervet** [comment]
Hi @HSULGIT , it is implemented in the lastest version.
The trustedDomains.js is updated in the readme.
I also need it for some use case to retrieve accesstoken  in a webpage to be used as a cli token once copied by user.

**Comment by HSULGIT** [comment]
Hi @guillaume-chervet , thank you for implementing it.

It seem to be configured in the react example but the access token on the profile page is secured by service worker anyway. In my own project i got the same problem. Serviceworker is updated and the dependency also. What could be wrong?

**Comment by guillaume-chervet** [comment]
hi @HSULGIT ,

did you try this page?

![image](https://github.com/AxaFrance/react-oidc/assets/52236059/16c47ac7-ddba-4776-b957-e5ebdac78781)

**Comment by HSULGIT** [comment]
I see, thank you. But actually i got Errors in Browser when using 'configurationName="config_show_access_token"' in the OidcProvider.

caught Error: OIDC library does seem initialized.
Please checkout that you are using OIDC hook inside a <OidcProvider configurationName="default"></OidcProvider> compoment.
 
 It seems that it doesnt take this configuration name and i dont understand why atb the moment.

**Comment by HSULGIT** [comment]
I got the fix. It was because of wrong configured OidcServiceWorker.js. Blame on me, wow that took me 3 days.

**Comment by hsul-git** [comment]
Hi @guillaume-chervet, that's fine by me.

**Comment by guillaume-chervet** [comment]
Hi @krzempekk , i close the issue  Feel free to reopen it if needed.
