### ISSUE TITLE
Coordinated token renewal when multiple tabs visible

### ISSUE THREAD

**Issue by krzempekk** [AxaFrance/react-oidc#1039]
### Issue and Steps to Reproduce

When multiple tabs with same app are opened (and service worker is used), but only one of them is visible, token renewal request is done only once - by visible tab, other tabs wait. If user switch to one of them, they receive newest tokens updated by other tab (`TOKEN_UPDATED_BY_ANOTHER_TAB_TOKENS_VALID` event).

This is not true when multiple tabs are visible at the same time (for example on two monitors). In that case, all visible tabs send token renewal request. This is unwanted behaviour, since there should be only one token renewal request. Also, sometimes some of visible tabs have delay and before they manage to do request, other tab already completes renewal flow and they receive tokens, so we have race condition here.

We found that `synchroniseTokensAsync` function from `packages/react/src/oidc/vanilla/oidc.ts` checks `document.hidden` variable - if it is true then tab waits. Simple fix for scenario with multiple visible tabs could be to also include check for `document.hasFocus()` - and perform refresh only if tab is currently focused. Only one tab can be focused at any given moment (but multiple can be visible), so only one token renewal request will be performed.

### Versions

6.16.14

#### Expected

Only one token renewal request is performed for given app, regardless of how many tabs are opened and visible.

#### Actual

Multiple token renewal request are performed when multiple tabs are visible.

**Comment by guillaume-chervet** [comment]
Hi @krzempekk , thank you again for your issue.
Thank you i haven't tougth about this scénario.
I can add a random delay time like in hidden mode to prevent refresh collision.

**Comment by krzempekk** [comment]
Hi @guillaume-chervet! 
Thank you for response, I think solution that you proposed will work for us :).

**Comment by krzempekk** [comment]
Hi @guillaume-chervet! 
Thank you! Will update to 6.17.0 and check it on my side.

**Comment by ampratt** [comment]
@guillaume-chervet  i have the same issue that when more than 1 tab/window is open it always logs out one tab. tried on V6.17.0 and latest 6.19.2 with the same results

**Comment by guillaume-chervet** [comment]
Hi @ampratt , do you have a sample of your configuration ?

**Comment by ampratt** [comment]
config is
`{
      isSet: false,
      client_id: "my-app",
      redirect_uri: `http://${window.location.host}/authentication/callback`,
      response_type: "code",
      post_logout_redirect_uri: `http://${window.location.host}/`,
      scope: "openid profile email ...",
      authority: "https://idp.my.com/auth/realms/test",
      silent_redirect_uri: `http://${window.location.host}/authentication/silent_callback`,
      automaticSilentRenew: true,
      loadUserInfo: true,
      refresh_time_before_tokens_expiration_in_second: 40,
      service_worker_only: false,
    };`
    
    running react v17 with Vite
