### ISSUE TITLE
Custom header on OIDC provider requests

### ISSUE THREAD

**Issue by julioisaac** [AxaFrance/react-oidc#1043]
### Issue and Steps to Reproduce

Is it possible to include a custom header in lib's OIDC requests?

### Versions

6.16.10

**Comment by guillaume-chervet** [comment]
Hi @julioisaac , thank yous for your issue.
It is not possible for the moment but it is a feature i would like to add. To be able to inject a custom fetch to react oidc.

I am curious, why do you need to inject custom headers?

**Comment by guillaume-chervet** [comment]
hi @julioisaac,

You can in the latest version inject fetch function : 

https://github.com/AxaFrance/react-oidc/blob/ce9be15db8e703d95cd059ab9d03c89e26c859fe/packages/react/src/MultiAuth.tsx#L13

**Comment by krzempekk** [comment]
Hi @guillaume-chervet ! I was updating to newest version and noticed that example in readme (https://github.com/AxaFrance/react-oidc/blob/master/packages/vanilla/README.md#getting-started) is probably wrong - there is:
```const vanillaOidc = VanillaOidc.getOrCreate(fetch)(configuration);```
, but based on the type I think it should be:
```const vanillaOidc = VanillaOidc.getOrCreate(() => fetch)(configuration);```

**Comment by guillaume-chervet** [comment]
Yes @krzempekk , thank yoi for the feedback.

**Comment by guillaume-chervet** [comment]
@julioisaac is everything  orking for you? May we close the issue?

**Comment by guillaume-chervet** [comment]
hi @krzempekk I have updated the documentation.

 @julioisaac I close the issue. Thank you for it. Feel free to reopen it if your need it.
