### ISSUE TITLE
Add possibility to turn off domain validation in service worker mode

### ISSUE THREAD

**Issue by krzempekk** [AxaFrance/react-oidc#1052]
### Issue and Steps to Reproduce

For some applications OIDC domain and endpoints are unknown before runtime. That makes it impossible to use this library with service worker enabled, since service worker checks whether OIDC endpoints are allowed in `OidcTrustedDomains.js` file and error is thrown if they are not - [here](https://github.com/AxaFrance/react-oidc/blob/master/packages/react/service_worker/OidcServiceWorker.ts#L295-L304). It would be very helpful if there would be boolean flag which allows to skip this exact check (`skipOidcServerDomainCheck` or something like that).

### Versions

6.17.1

#### Expected

If OIDC server domain is not present in `OidcTrustedDomains.js`, error is thrown in service worker mode.

#### Actual

Mentioned error is not thrown if flag `skipOidcServerDomainCheck` is set to true.

**Comment by guillaume-chervet** [comment]
hi @krzempekk ,

Thank you again fro your issue.
You can already use "*" un domaines or use a Custom regex. 
But it is not very secure.

The best i think is to dynamically construct your TrustedDomains.js from server side and add the exact TrustedDomains.

**Comment by guillaume-chervet** [comment]
Hi @darkowic yes because it will open a security leak. 

What i can do is to allow trustedDomain variable to also be a promise so you can fetch somewhere to build it dynamically.
Is this solution will work for you?

**Comment by krzempekk** [comment]
Hi @guillaume-chervet! Unfortunately, trustedDomain variable as a promise will not work for us.
However, we came up with alternative proposition. AFAIU, domain list is used in two places:
- to validate `OidcServerConfiguration` (or skip that validation if "*" is used)
- to determine whether to attach access token to given request (or attach to any request if "*" is used)

My proposition would be to allow specyfing domain list separately for those two concerns. In this PR you have extended TrustedDomains type to allow not hiding access token:
https://github.com/AxaFrance/react-oidc/pull/1046/files#diff-4e0fa21f4a666dba472c1f857162f26746a97c6a84dbf632458c6c39180a49f1R1
My proposition is to change `DomainDetails` type to be:
```
type DomainDetails = {
    domains: Domain[];
    oidcDomains: Domain[];
    accessTokenDomains: Domain[];
    showAccessToken: boolean;
};
``` 
And adjust the logic so that:
- when OIDC domains are verified, first `oidcDomains` are checked and if it is not specified `domains`
- when domains to attach access token are determined, first `accessTokenDomains` are check and if it is not specified `domains`

Pros of that solution:
- better separation of concerns - we can define explicitly which domains are used by OIDC and which are APIs that require access_token
- our case of turning off domain validation can be solved by passing `oidcDomains: ["*"]`, while not introducing security leak
- no breaking changes are introduced

**Comment by guillaume-chervet** [comment]
hi @krzempekk , 
I have re-read your post many times and I think I'am not sure to understand your idea.

Do you have an Example configuration to explain you idea ? with sample of call to some urls.

**Comment by krzempekk** [comment]
Hi @guillaume-chervet! Thanks for your response, let me elaborate more and illustrate with examples.

Example 1.
TrustedDomains file content:
```
const trustedDomains = {
  default: { oidcDomains: ["http://myoidc/"], accessTokenDomains: ["http://myapi/"] }
}
```
Client sends OidcAuthorizationServiceConfiguration with endpoints from `http://myoidc/` domain to service worker. SW accepts it, because `http://myoidc/` is part of `oidcDomains` list. 
If OidcAuthorizationServiceConfiguration contained endpoints from `http://myapi/` domain (which might have been set by mistake using manual authority configuration), SW won't accept those, because `http://myapi/` is not in `oidcDomains` list. 
Later client makes request to `http://myapi/data`. `http://myapi/` is in `accessTokenDomains` list, so access token is added to request.
Client makes another request to `http://randomapi/data`. `http://randomapi/` is not in `accessTokenDomains` list, so access token is not added to request.

Example 2.
TrustedDomains file content:
```
const trustedDomains = {
  default: { oidcDomains: ["*"], accessTokenDomains: ["http://myapi/"] }
}
```
In this case, SW accepts any OidcAuthorizationServiceConfiguration, it doesn't check what endpoints domains.
Access token, however, is still appended only to domains from `accessTokenDomains` list.

Example 3.
TrustedDomains file content:
```
const trustedDomains = {
  default: { oidcDomains: ["http://myoidc/"], accessTokenDomains: ["*"] }
}
```
In this case, SW accepts only OidcAuthorizationServiceConfiguration, which contains endpoints from domains from `oidcDomains` list.
Access token, however, is appended to all requests, regardless of domains.

Example 4.
TrustedDomains file content:
```
const trustedDomains = {
  default: { oidcDomains: ["*"], accessTokenDomains: ["*"] }
}
```
This is equivalent to `default: { domains: ["*"] }`.

Example 5.
TrustedDomains file content:
```
const trustedDomains = {
  default: { domains: ["http://whatever/"],  oidcDomains: ["http://myoidc/"], accessTokenDomains: ["http://myapi/"] }
}
```
This is equivalent to Example 1. `domains` list is present, but `oidcDomains` and `accessTokenDomains` take precedence,

Example 6.
TrustedDomains file content:
```
const trustedDomains = {
  default: { domains: ["http://whatever/"], accessTokenDomains: ["http://myapi/"] }
}
```
`oidcDomains` list is not present, so SW accepts only OidcAuthorizationServiceConfiguration with endpoints from `domains` list.
Access token is appended only to domains from `accessTokenDomains` list.

Example 7.
```
const trustedDomains = {
  default: { domains: ["http://whatever/"],  oidcDomains: ["http://myoidc/"] }
}
```
SW accepts only OidcAuthorizationServiceConfiguration with endpoints from `oidcDomains` list.
`accessTokenDomains` list is not present, so access token is appended only to domains from `domains` list.

Hope my idea is a bit more clear now. Please let me know if you still have some questions :D.

**Comment by krzempekk** [comment]
Hi @guillaume-chervet!
Any thoughts on the above? If this solution is acceptable for you we will gladly implement it and open PR to your repo 😄

**Comment by guillaume-chervet** [comment]
Hi @krzempekk , i did not get time to study your solution. I look at it on monday.

**Comment by guillaume-chervet** [comment]
Hi @krzempekk , I like your idea.

Very sorry for the delay. Life with children is cool but I'am lacking of sleep and time ^^

Is it possible to pass by defaut the access_token to the OIDC user endpoint?

For example in the demo:

const trustedDomains = {
  default: { oidcDomains: ["https://demo.duendesoftware.com"], accessTokenDomains: ["http://myapi"] }
}

to let pass the access_token from userinfo endpoint :
https://demo.duendesoftware.com/connect/userinfo

![image](https://github.com/AxaFrance/react-oidc/assets/52236059/ad9a16f9-fc56-4f29-a49e-4dd2e9270ec8)

**Comment by krzempekk** [comment]
Hi @guillaume-chervet! 
No worries :D. Thank you for response :D.

Yes, I think that would definitely make sense to pass access_token to domains from `oidcDomains` as well, because otherwise those domains would need to be duplicated - in `oidcDomains` and `accessTokenDomains`.
So, your example:
```
const trustedDomains = {
  default: { oidcDomains: ["https://demo.duendesoftware.com"], accessTokenDomains: ["http://myapi"] }
}
```
Would be functionally equivalent to:
```
const trustedDomains = {
  default: { oidcDomains: ["https://demo.duendesoftware.com"], accessTokenDomains: ["https://demo.duendesoftware.com", "http://myapi"] }
}
```
`oidcDomains` would be automatically appended to `accessTokenDomains` without need to explicitly add them there.

One exception here, in following scenario:
```
const trustedDomains = {
  default: { oidcDomains: ["*"], accessTokenDomains: ["http://myapi"] }
}
```
`oidcDomains` would not be appended to `accessTokenDomains`, because that would mean that access_token should be appended to ALL requests (and proper configuration for this behaviour is `default: { oidcDomains: ["*"], accessTokenDomains: ["*"]`).

Does that make sense? :D

**Comment by guillaume-chervet** [comment]
Hi @krzempekk , i am not fan to copy oidcDomains to accessTokenDomains. I prefer a specific case for userinfo endpoint.

I am curieuse. For which use case do you need this evolution?
In you case do you have dynamic oidcDomains or dynamic api endpoint?

**Comment by krzempekk** [comment]
Hi @guillaume-chervet !

I misunderstood your previous comment - if appending access token to userInfo endpoint is enough, we don't need to copy oidcDomains to accessTokenDomains. We can just provide support for that specific case.

As for our use case, there is no need for merging oidcDomains with accessTokenDomains, ability to define them separately (as discussed in previous comment) is good enough.

**Comment by krzempekk** [comment]
Hi @guillaume-chervet !

I have just opened a PR implementing solution which we have discussed. I will appreciate some review 😄. I hope that I applied changes to all required places, but I might have missed something.

**Comment by guillaume-chervet** [comment]
hi @krzempekk , may we close the issue resolved by you ?

**Comment by krzempekk** [comment]
Great, thank you! :)

**Comment by guillaume-chervet** [comment]
last version was just published, there was a problem. Thank you @krzempekk for your help.
