### ISSUE TITLE
CORS error on refresh and revoke token requests

### ISSUE THREAD

**Issue by ampratt** [AxaFrance/react-oidc#1054]
### Issue and Steps to Reproduce

After migrating from the old package ( @axa-fr/react-oidc-context ) which is now deprecated to this one, my login process works normally, but token refresh and revoke requests fail with a CORS error from my keycloack idp, and then kicks the users out of the application.

I have `localhost:3000/*` added in my keyclock valid redirect URIs and the Web Origins is set to +

### Versions

6.19.0

### Screenshots
![image](https://github.com/AxaFrance/react-oidc/assets/6746269/57fc700e-94a7-4732-81ef-fe818a4d7040)

![image](https://github.com/AxaFrance/react-oidc/assets/6746269/9e50fd53-fc44-45ca-9bfb-f5bd9ac772d3)

#### Expected
to silently refresh in the background without the users noticing and not logging out.

### Additional Details

- Installed packages:

React v. 17.x
Vite v. 4.1.4

**Comment by guillaume-chervet** [comment]
Hi @ampratt , thank you for your issue.

Which configuration do you use? With Service worker or default?
A pullrequest was merged yesterday about service worker and modify something near your issue. It is may be a regression. Then version  6.18.2 may work.
Does you urls are declared inside keycloack configuration?

**Comment by ampratt** [comment]
Thank you for the quick response!
I was on version 6.17.x until this morning. I was hoping the latest code would fix the issue but it didn't. the issue wasalready happening on 6.x

I am using the default config, is that with or without service worker? at least it is not service worker only.
here is my config. when using the before mentioned deprecated package, automatic refresh was happening normally.
```
{
      client_id: "my-app",
      redirect_uri: `http://${window.location.host}/authentication/callback`,
      response_type: "code",
      post_logout_redirect_uri: `http://${window.location.host}/`,
      scope: "openid profile email ...",
      authority: "https://<my keyclock>/auth/realms/test",
      silent_redirect_uri: `http://${window.location.host}/authentication/silent_callback`,
      refresh_time_before_tokens_expiration_in_second: 30,
      automaticSilentRenew: true,
      loadUserInfo: true,
};
```

**Comment by guillaume-chervet** [comment]
Hi @ampratt , you configuration does not seem up to date with last configuration.
Checkout the lastest readme https://www.npmjs.com/package/@axa-fr/react-oidc
I will try to configure a keycloack next monday.

**Comment by ampratt** [comment]
Hi @guillaume-chervet . I checked out the latest readme, everything looks to be ok.
Do you think that it would make a difference between using serviceWorker mode or not? Any other updates on this issue?

**Comment by ampratt** [comment]
I believe i found the issue. This is lame. I never noticed the end of the error message in the logs complaining of a request header not allowed by keycloak. Our application has a couple custom headers we use for varios functions, some of which were recently added.

![image](https://github.com/AxaFrance/react-oidc/assets/6746269/80dff72c-fe2b-4a1d-83e8-cc69e396fe36)

after the first initial quick test, refresh tokens seem to work when I do not add the headers to calls to idp.

I will test further in production environments and then close this if the issue is indeed resolved.

**Comment by guillaume-chervet** [comment]
Thank you @ampratt for the feedback. I hope it will resolve well your issue!

**Comment by guillaume-chervet** [comment]
hi @ampratt , may we close the issue?

**Comment by ampratt** [comment]
looks like this is resolved. thank you
