### ISSUE TITLE
OidcServiceWorker refreshTokenAsync:

### ISSUE THREAD

**Issue by danway2012** [AxaFrance/react-oidc#1057]
Hello, sorry to bother you again. I think there is an issue with OidcServiceWorker. I was testing the behaviour of refreshTokensAsync with:

{events.map(e => {
                const date = new Date(e.date);
                const dateFormated = `${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`;
                return <Card key={e.id}>{dateFormated} {e.name}: { JSON.stringify(e.data)}</Card>;
              })}

sometimes retrieve me the following error:
oidc:default:refreshTokensAsync: {"message":"wait because navigator is hidden try {number}"}.

My configuration is:

export const configuration={
    client_id: 'client_id',
    redirect_uri: `${window.location.origin}/authentication/callback`,
    silent_redirect_uri: `${window.location.origin}/authentication/silent-callback`, // Optional activate silent-signin that use cookies between OIDC server and client javascript to restore the session
    scope: 'openid all',
    authority: authority....',
    token_request_extras: {
        client_secret: 'client_secret',
    },   
    service_worker_relative_url:'/OidcServiceWorker.js',
    service_worker_only:true,
    extras:{
        'resource:token_request': 'resource',
	     resource: 'resource'
      },
    token_renew_mode: TokenRenewMode.access_token_or_id_token_invalid,

 }

This cause conflicts with Logout for example, because sends to the authorizationService an invalid token

Do you know why is this happening? 

Thanks for the help :)

**Comment by guillaume-chervet** [comment]
hi @danway2012 ,

The message oidc:default:refreshTokensAsync: {"message":"wait because navigator is hidden try {number}"}.
is normal and happen when page is not displayed to the screen. In that case some Fetches can be so delayed by browsers that they quasi always fail.

For the logout it is interresting. 
We are using parameter ?endSessionId= to set the idToken but I do not know about "sid".
There is many logout flow with OIDC, did you configured the front side logout flow?

**Comment by danway2012** [comment]
Hi @guillaume-chervet thanks for your answer. The front side logout is the following:
![image](https://github.com/AxaFrance/react-oidc/assets/80462934/aeea6c87-ea52-4126-8d19-f730284a9286)

This issue happens sometimes, and when ocurred, it's with this event:

oidc:default:refreshTokensAsync: {"message":"wait because navigator is hidden try {number}"}.
I think it's happening because oidc library send an invalid token to end_session_endpoint of Authorization Server.




P.S.: Sid refers to Session ID

**Comment by guillaume-chervet** [comment]
hi @danway2012 ,

Thank you for your feedbacks. Other OIDC servers I have used accept not valid openid token for logout.
Yes it is possible to add this enhancement.

**Comment by danway2012** [comment]
Perfect, thanks you!. To fixed this error with the current version, what could I do?

**Comment by guillaume-chervet** [comment]
Hi @danway2012 , temporary you may set not clickable logout when idtoken is not valid.
It should happen only when you come back to your application after a period of inactivity. It should be short.

**Comment by danway2012** [comment]
@guillaume-chervet  sorry to disturb you again. Is there any method available in this library to ckeck if token is valid?

**Comment by guillaume-chervet** [comment]
Hi @danway2012 , 
The method is not expose by react-oidc but you can use, it should work it:https://github.com/AxaFrance/react-oidc/blob/12f114010febf394d92c5f3d712f826495fd59fa/packages/react/src/oidc/vanilla/parseTokens.ts#L131

**Comment by guillaume-chervet** [comment]
Hi @danway2012 , did you succed to import and use it?

**Comment by danway2012** [comment]
Hi @guillaume-chervet sorry for the late reply. I couldn't get it done due to an error with de TypeScript parser. I tried to fix the bug checking if token is still valid (similar way to your implementation). It works better but time to time error appears. I show you my implementation anyway:


![image](https://github.com/AxaFrance/react-oidc/assets/80462934/0392efa8-d345-4bf1-8e23-cfca6e10b643)

![image](https://github.com/AxaFrance/react-oidc/assets/80462934/ac953edc-16ff-4104-bd41-9412abee881f)

**Comment by danway2012** [comment]
Hi @guillaume-chervet do you know a better way of doing it? It still failing from time to time and I will like to troubleshoot it completely.

**Comment by danway2012** [comment]
In the backend part, I could manage to destroy the session with a token considered "no valid" revoking the token from server and client.

**Comment by guillaume-chervet** [comment]
Thank you @danway2012 for your feedback!
