### ISSUE TITLE
useOidcAccessToken always gets ACCESS_TOKEN_SECURED_BY_OIDC_SERVICE_WORKER_default

### ISSUE THREAD

**Issue by silencej** [AxaFrance/react-oidc#1058]
### Issue and Steps to Reproduce

OidcTrustedDomains.js set as README:

```js
const trustedDomains = {
  default:["https://demo.duendesoftware.com", "https://www.myapi.com/users"]
//  "https://demo.duendesoftware.com/connect/token", "https://demo.duendesoftware.com/connect/revocation", "https://demo.duendesoftware.com/connect/userinfo"
};

// Service worker will continue to give access token to the JavaScript client
// Ideal to hide refresh token from client JavaScript, but to retrieve access_token for some
// scenarios which require it. For example, to send it via websocket connection.
trustedDomains.config_show_access_token = { domains : ["https://demo.duendesoftware.com"], showAccessToken: true };
```

### Versions

16.9.0

### Additional Details

- Installed packages:

**Comment by silencej** [comment]
After going through the source codes, I find out there are two places in the README that are misleading:
1. default config has always set showAccessToken=false. So to showAccessToken, we need to use a non-default one. See https://github.com/AxaFrance/react-oidc/blob/e3d208f86eba26765e064db675fed2cc4f15c846/packages/react/service_worker/OidcServiceWorker.ts#L48
2. That's why in README we have: trustedDomains.config_show_access_token . But the README doesn't mention that we need to use "config_show_access_token" as the configName from then on.

Solution:

OidcTrustedDomains.js

```js
const trustedDomains = {
  config_show_access_token = { domains : ["https://demo.duendesoftware.com"], showAccessToken: true }
};
```

Then we should pass the configName in index.tsx:

```typescript
        <OidcProvider
          configuration={configuration}
          configurationName='config_show_access_token'
        >
          <App />
        </OidcProvider>
```

And everywhere we are using it:

```typescript
const oidcConfigName = 'config_show_access_token'
export function useAccessToken() {
  const token = useOidcAccessToken(oidcConfigName)
  return token
}
export function useOidc2() {
  const oidc = useOidc(oidcConfigName);
  return oidc
}
export function useOidcUser2() {
  const user = useOidcUser(oidcConfigName);
  return user
}
```

**Comment by guillaume-chervet** [comment]
hi @silencej, thank you for your feedback.

I have to enhance the documentation. 
The demo have a full sample of many configurations. I use it for the documentation:
https://black-rock-0dc6b0d03.1.azurestaticapps.net/multi-auth

**Comment by HSULGIT** [comment]
Is the documentation already enhanced? I have also problems to get the token visible.

**Comment by HSULGIT** [comment]
Even with his solution my auth seems to break. 

OidcServiceWorker.ts:291 Uncaught TypeError: Cannot read properties of undefined (reading 'showAccessToken')
    at $ (OidcServiceWorker.ts:291:111)

Maybe i should send the token to my backend and return it as a string, till there is a official solution for that.
