### ISSUE TITLE
What to do if you need another service worker?

### ISSUE THREAD

**Issue by GNUGradyn** [AxaFrance/react-oidc#1062]
Hello, this is more of a question about implementation. Consider the following scenario:
- You have a web app that uses this library to authenticate
- You want the app to work offline

This creates a problem. In order to make the app work offline, you would need to create a service worker to handle caching resources. However, this library uses a service worker to intercept requests and add the auth token - so these service workers would have the same scope

surely this is a solvable problem because I'm sure this is a common scenario, how is this typically handled?

**Comment by guillaume-chervet** [comment]
Hi @GNUGradyn ,
I already had this use case, but this pretty hard to do with progressive webapp.
We had to rethink all webapp UX to be deconnected.
And one part to synchronised with the API.
Its hard to tests and difficult to maitain.

**Comment by GNUGradyn** [comment]
Is there a way to use this library without the service worker? Or a way to edit its service worker without it getting overwritten?

**Comment by guillaume-chervet** [comment]
Yes @GNUGradyn , 

Just comment 

const configuration = { 
// service_worker_relative_url:'/OidcServiceWorker.js', service_worker_only:false};

On your local desktop you may need to remove manually service worker from chrome dev tool.

**Comment by GNUGradyn** [comment]
I was able to disable the service worker using @guillaume-chervets info, and use the OIDC libraries fetch instead. This worked but should probably be better documented

**Comment by guillaume-chervet** [comment]
Thank you @GNUGradyn  for the feedback!
