### ISSUE TITLE
Failed to register a ServiceWorker for scope, TypeError: Failed to register a ServiceWorker for scope 

### ISSUE THREAD

**Issue by tonyctsiu** [AxaFrance/react-oidc#1067]
### Issue and Steps to Reproduce

I got Uncaught runtime erros when running a simple test React with TSX template.
Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/OidcServiceWorker.js'): ServiceWorker script evaluation failed
TypeError: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/OidcServiceWorker.js'): ServiceWorker script evaluation failed
### Versions
The source code I written can be downloaded from Git hub:
https://github.com/tonyctsiu/oidctest.git

`const configuration = {
  client_id: "oidc-client",
  redirect_uri: window.location.origin + "/authentication/callback",
  silent_redirect_uri:
    window.location.origin + "/authentication/silent-callback", // Optional activate silent-signin that use cookies between OIDC server and client javascript to restore the session
  scope: "product.read product.write",
  authority: "http://localhost:9001",
  service_worker_relative_url: "/OidcServiceWorker.js",
  service_worker_only: true,
};`
### Screenshots
![run time error](https://github.com/AxaFrance/react-oidc/assets/12131338/6ab209c0-fc1b-4541-a03e-66193da0dd3f)

### Additional Details

- Installed packages:
`{
  "name": "testprogram",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@axa-fr/react-oidc": "^6.19.2",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.35",
    "@types/react": "^18.2.10",
    "@types/react-dom": "^18.2.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.12.1",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by guillaume-chervet** [comment]
Hi @tonyctsiu , thank you very much for your issue.
It seems your TrustedDomains.js file is missing inside your public folder.
It is an issue from us. It should be created automaticaly during nom install.

Create and configure it and then it should work!

**Comment by tonyctsiu** [comment]
Thanks Guillaume. It works..
