### ISSUE TITLE
[feature request] Customizable timeout time on the well-known configuration fetch. 

### ISSUE THREAD

**Issue by tielushko** [AxaFrance/react-oidc#1069]
### Issue and Steps to Reproduce

I am trying to implement basically two versions of the same application. One application that is access through mobile, we don't care about the presence of the OidcProvider wrapper, and I would like the application to appear right away, without waiting for the success/failure of the well-known url. 

On the other hand, the version of the same app that's run on desktops would care about well known url and when it's fetched. 

I was wondering if a custom timeout could be added to fetchFromIssuer function call. Currently, it's using a plain fetch function with no handling for timeouts or anything of that sort. 

https://github.com/AxaFrance/react-oidc/blob/89d7ae887a0c0d9fb220b85d18c57791fbe2746d/packages/react/src/oidc/vanilla/requests.ts#L8

Please let me know if that would be possible.

Best, 
Oleg T. 

### Screenshots
<img width="735" alt="image" src="https://github.com/AxaFrance/react-oidc/assets/46033508/2fefd05b-75b4-4b3f-8d4c-50238aa882ef">

#### Expected

I would also expect the fetchFromIssuer to use token_timeout property in the config, or something of similar nature. 

#### Actual

The token/silent sign in request timeouts specified in the config do not affect the fetchFromIssuer endpoint timeout. 

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @tielushko , thank you for your well described issue.
Yes is is possible to add a configurable timeout on the fetch issue.
What will you do in case of timeout?
I think it is pretty Quick to add.

**Comment by tielushko** [comment]
Ideally we could throw an error in case the timeout happens. However, I am seeing right now that the code returns null whenever the error happens. My mobile version of the app is just a dashboard solution that won't require authentication as such doesn't have access to internal oidc provider. However, that initial fetch for oidc config increases the page load time on mobile significantly.

If it has the current behavior, I would be ok with that. If it returns an error that I could handle on my end, I would be ok with that too.  I raised an issue here earlier about throwing an error: [https://github.com/AxaFrance/react-oidc/issues/994](url)

**Comment by guillaume-chervet** [comment]
Hi @tielushko , i did not get time to look at this today. I will do it on monday.

**Comment by guillaume-chervet** [comment]
hi @tielushko ,

I have added the feature => https://github.com/AxaFrance/react-oidc/commit/7847c705d62b3d7d0f35f649335178569a732fff

If timeout is elapsed, the error component is triggered.

**Comment by tielushko** [comment]
@guillaume-chervet Thank you for adding the feature. I left a couple of comments as there was a typo in config property. 

Thanks!

**Comment by guillaume-chervet** [comment]
Thank you @tielushko , i fixed the documentation. 
I will enhance the global documentation very soon.
