### ISSUE TITLE
How to use local storage with react-oidc to remember active session/accesstoken after browser close?

### ISSUE THREAD

**Issue by hsul-git** [AxaFrance/react-oidc#1073]
Hello,

i have a question and hope you can help me.

how can i redeem the needed data from react-oidc to save them in local storage? And how do i feed in the data after a browser close and reopen? 

At the moment my page "forgets" that there is a open session and force me to login again after i completely closed my browser and open it again. Is there a specific solution for that?

Thank you for helping.

Greetings HSUL

**Comment by guillaume-chervet** [comment]
hi @hsul-git ,

Thank you for your issue. You can acitvate localStorage as default mode


storage: localStorage,
and remove service worker mode
// service_worker_relative_url: '/OidcServiceWorker.js',
// service_worker_only: false,

It should work as you expect but you loose a lot in security.

**Comment by hsul-git** [comment]
Hi @guillaume-chervet,

thank you for your answer.

I configured it like this:

const configuration = {
  storage: localStorage, 
  client_id: envVarAuthClient ? envVarAuthClient : '',
  redirect_uri: window.location.origin + "/authentication/callback",
  silent_redirect_uri:
    window.location.origin + "/authentication/silent-callback", // Optional activate silent-signin that use cookies between OIDC server and client javascript to restore the session
  scope: "openid profile email",
  refresh_time_before_tokens_expiration_in_second: -86300,
  authority: envVarAuthProvider ? envVarAuthProvider : '',
  service_worker_relative_url: "/OidcServiceWorker.js",
  service_worker_only: false,
};

But if i reopen my browser i get redirected to the login again. My page checks on loadup if the user is loggedin or not and redirect directly to the login if not, else to the memberarea. Is there something missing? Do i have to inject informations from react-oidc into the LocalStorage and extract them later?

**Comment by guillaume-chervet** [comment]
Hi @hsul-git , you need to comment service worker property to disable it

**Comment by guillaume-chervet** [comment]
You will need also to remove service worker from browser Web tool @hsul-git

**Comment by hsul-git** [comment]
Perfect, thank you for your response. It just works fine now. Thank you!!!

**Comment by guillaume-chervet** [comment]
hi @hsul-git , thank you for your feedback, may we close the issue?

**Comment by hsul-git** [comment]
Hi @guillaume-chervet, yes thank you for your help!
