### ISSUE TITLE
State is not valid in Safari

### ISSUE THREAD

**Issue by JakubKacik** [AxaFrance/react-oidc#1079]
### Issue and Steps to Reproduce
There is an issue with a very short timeout to perform login action in Safari. When login actions takes approximately more than 30 sec then invalid state error is occurring. 

In Chrome there is no problem.

It is reproducible also in demo app with default settings.

1. Click to Login
2. Redirect to Identity Server
3. Wait some time and then Login
4. After redirection back to client there is an error 

### Versions
react-oidc: 6.23.0
Safari: 16.3

### Screenshots
<img width="283" alt="Screenshot 2023-06-30 at 14 07 11" src="https://github.com/AxaFrance/react-oidc/assets/29824390/f76d74ca-2abb-4c8d-87c0-be7f7a59b5eb">

### Expected
Successful redirect to client application

### Actual
<img width="473" alt="Screenshot 2023-06-30 at 14 02 39" src="https://github.com/AxaFrance/react-oidc/assets/29824390/f58d5afd-e491-4a5f-9eba-4eab5ecb0863">

**Comment by guillaume-chervet** [comment]
Hi @JakubKacik , thank you for your issue.
Do you have a sample of your configuration?

**Comment by JakubKacik** [comment]
Hi @guillaume-chervet. It is default configuration for demo react project in you package.

<img width="657" alt="Screenshot 2023-06-30 at 21 31 38" src="https://github.com/AxaFrance/react-oidc/assets/29824390/70e30d1b-b2bc-4a95-9ff4-28ca26b565dd">

**Comment by guillaume-chervet** [comment]
Thank you @JakubKacik i need to analyse to find the best solution. 
Do you need service worker mode? I can disable it temporary on safari. The time to find solution.

**Comment by JakubKacik** [comment]
I think that I am able to use it without service worker until you will find the solution. 

Thank you.

**Comment by guillaume-chervet** [comment]
hi @JakubKacik ,

I think I have resolve it int the PullRequest #1084 .

Does the demo work for you on iOS? https://black-rock-0dc6b0d03-1084.westeurope.1.azurestaticapps.net/

**Comment by JakubKacik** [comment]
Hi @guillaume-chervet,

unfortunately, there is another authentication error. 

<img width="711" alt="Screenshot 2023-07-09 at 16 36 19" src="https://github.com/AxaFrance/react-oidc/assets/29824390/3d78c65d-1297-4d66-955c-b1d44c09d12b">

**Comment by guillaume-chervet** [comment]
Thank you @JakubKacik for the feedback. I may need to affine the pullrequest :p

**Comment by guillaume-chervet** [comment]
hi @JakubKacik ,

Do you still have the problem on the lastest demo from the PullRequest? 
https://black-rock-0dc6b0d03-1084.westeurope.1.azurestaticapps.net/

**Comment by JakubKacik** [comment]
Hi @guillaume-chervet,

Now it is working as expected, thank you. I tried it with 1 minute redirect delay and authentication was successful.

**Comment by guillaume-chervet** [comment]
I close the issue @JakubKacik. Feel free to reopen it if needed.
And again thank you very much for your issue !
