### ISSUE TITLE
Support for defaultProps will be removed from function components

### ISSUE THREAD

**Issue by pimjansen** [AxaFrance/react-oidc#1083]
Im getting this warning while running the application in its default form:

### Issue and Steps to Reproduce

app-index.js:31 Warning: OidcRoutes: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at OidcRoutes (webpack-internal:///(app-client)/./node_modules/@axa-fr/react-oidc/dist/core/routes/OidcRoutes.js:36:23)
    at Switch (webpack-internal:///(app-client)/./node_modules/@axa-fr/react-oidc/dist/OidcProvider.js:39:19)
    at OidcProvider (webpack-internal:///(app-client)/./node_modules/@axa-fr/react-oidc/dist/OidcProvider.js:46:25)
    at Auth (webpack-internal:///(app-client)/./src/components/Auth.tsx:19:11)
    at body

### Versions
"@axa-fr/react-oidc": "^6.23.1"

### Additional Details

- Installed packages:
```
    "@axa-fr/react-oidc": "^6.23.1",
    "@types/node": "20.3.3",
    "@types/react": "18.2.14",
    "@types/react-dom": "18.2.6",
    "autoprefixer": "10.4.14",
    "eslint": "8.44.0",
    "eslint-config-next": "13.4.8",
    "next": "13.4.8",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "5.1.6"
```

**Comment by guillaume-chervet** [comment]
Oh thank you for this issue @pimjansen .
I will try to fix it quickly.

**Comment by pimjansen** [comment]
> Oh thank you for this issue @pimjansen .
> 
> I will try to fix it quickly.

Ah great! Yeah it still works fine but im always getting a bit scared since it is shown as error in the console haha

**Comment by guillaume-chervet** [comment]
Hi @pimjansen ,

The latest version should be OK.

**Comment by pimjansen** [comment]
Great? Is it on dev master or already released?

**Comment by guillaume-chervet** [comment]
Hi @pimjansen , yes it is on master. Published on npm.

**Comment by pimjansen** [comment]
> Hi @pimjansen , yes it is on master. Published on npm.

👌🏻
