### ISSUE TITLE
PKCE doesn't seem to work with private address and http

### ISSUE THREAD

**Issue by mlsmaycon** [AxaFrance/react-oidc#1116]
### Issue and Steps to Reproduce

I am having an issue using the library to authenticate against a private address using http and PKCE. I want to confirm if this is the intended behavior for v5.

### Versions
5.14.2
### Authorization request

http://10.87.57.31/oauth/v2/authorize?redirect_uri=http%3A%2F%2F10.87.57.31%2Fnb-auth&client_id=225454874660299524%40netbird&response_type=code&state=nVWV5AKymU&scope=openid%20profile%20email%20offline_access&audience=225454874660299524%40netbird

#### Expected
the query parameters should be part of the authorization request above: 
code_challenge=mOb96G7QxwR_gie7uU5NEppbKrfb_QDeq3yBjUk-NlU&code_challenge_method=S256
### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @mlsmaycon ,

OIDC should be use with https 
The library works wellnin dev mode with HTTP.

Your issue may be LinkedIn to your OIDC provider rule.
What is your current error?

**Comment by mlsmaycon** [comment]
The error is just `code_challenge required` and it seems to be caused by the FE not sending the PKCE challenges in the first authorize request.

With the same IDP configuration, using localhost works fine and the request URL is complete:

```
http://10.87.57.31/oauth/v2/authorize?redirect_uri=http%3A%2F%2Flocalhost%2Fnb-auth&client_id=225454874660299524%40netbird&response_type=code&state=3hy9zORENA&scope=openid%20profile%20email%20offline_access&audience=225454874660299524%40netbird&code_challenge=fzrZC-k81OdtikD39z0TZCF1KyUH9Ifz-kXABOPErzs&code_challenge_method=S256
```

**Comment by guillaume-chervet** [comment]
Do you have the same kind of error like this issue : https://github.com/AxaFrance/react-oidc/issues/1028
?

**Comment by mlsmaycon** [comment]
I do:
<img width="1509" alt="image" src="https://github.com/AxaFrance/react-oidc/assets/7747744/09e311af-6779-4667-b85b-6d7f65d9528c">

The solution is to upgrade?

**Comment by guillaume-chervet** [comment]
I think you need to switch to HTTPS. I do not have better solution.

**Comment by mlsmaycon** [comment]
Ok, thanks for your help. 

Also, really appreciate your time working on this amazing library.
