### ISSUE TITLE
[Feature request] Access rest of claims via oidcUser

### ISSUE THREAD

**Issue by GNUGradyn** [AxaFrance/react-oidc#976]
Hello. I like the ability to keep the token isolated to the service worker and access claims via oidcUser. However, it only gives access to a select few claims. For an example, keycloaks "Realm Access" claims are not accessible so you cannot determine what roles a user belongs to. 
![image](https://user-images.githubusercontent.com/20762604/222545326-4f8fb43d-122e-43bf-92ac-20c3d1bedca3.png)
Why can't it just include all claims? As long as the signature is not included I don't see how this presents an CSRF risk.

**Comment by guillaume-chervet** [comment]
hi @GNUGradyn ,

if your claims are set in JWT Access Token or ID token then your have access to it via the available payload.

Checkout the demo : https://black-rock-0dc6b0d03.1.azurestaticapps.net/

**Comment by guillaume-chervet** [comment]
Hi @GNUGradyn , did this solved your issue?

**Comment by GNUGradyn** [comment]
yes, thank you
