### ISSUE TITLE
Question: watching the access token while debugging

### ISSUE THREAD

**Issue by raffaeler** [AxaFrance/react-oidc#992]
### Issue and Steps to Reproduce
I see that the access token has been hidden for good reasons.
Anyway, while debugging, it is important to sneak into it to understand the token structure.

The obvious workaround is to put a console.log into the service worker.
Instead, I am wondering whether there is a nicer way to propagate the token to react so that I can print it on the debug page instead of the developer tools console.

### Versions
6.15.8

TIA

**Comment by raffaeler** [comment]
I figured out how to do this. I write this here in case it could help someone else:
```javascript
import { useOidcIdToken, useOidcAccessToken } from '@axa-fr/react-oidc';
...
const { accessToken, accessTokenPayload } = useOidcAccessToken();
...
// use the accessTokenPayload object to access claims and whatever else
```

**Comment by raffaeler** [comment]
One more thing please.
How can I access instead the refresh_token (for debug purposes)?

**Comment by guillaume-chervet** [comment]
Hi @raffaeler ,
Thank you for your issue.
You can get the refreshToken from network debug tab.
You will see tokens sended by your oidc server and you can see tokens injected by the service worker.

**Comment by raffaeler** [comment]
Thank you @guillaume-chervet but I am giving a demo where I have a debug page showing the tokens and few other things.
While I totally agree on securing the tokens, I would prefer to access them for this specific scenario in my code.

**Comment by guillaume-chervet** [comment]
Hi @raffaeler , refreshtoken is not accessible from javascript in serviceworker mode.
If you disable service worker you can access the tokens from sessionstorage or localstorage if your configured it.
