### ISSUE TITLE
Requests that are handled by the ServiceWorker do not get canceled

### ISSUE THREAD

**Issue by Zamaletdinov** [AxaFrance/react-oidc#995]
### Issue and Steps to Reproduce
I was asked to implement cancellation for some long-running requests. We use Axios to handle requests and try both options from the [documentation](https://axios-http.com/docs/cancellation) - neither CancelToken (deprecated) nor AbortController is being respected. Removing the library does fix the issue, but it is not an option 😄 

Not sure which steps to describe, except trying to make a request and cancel it via CancelToken/AbortController

### Versions

- "@axa-fr/react-oidc": "^6.15.5",
- "axios": "^1.3.4"

### Screenshots
The request was invoked
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/8142668/225068950-487614ff-f11b-4f7b-a198-79aa08b5b144.png)

Axios canceled the request
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/8142668/225069151-199a6ca3-774c-45a0-85e2-386eec6342ad.png)

The request created by the ServiceWorker failed eventually
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/8142668/225069366-08cc707c-4759-4ca8-a011-5bcb3fecf24c.png)

#### Expected
The request should be canceled (the image was taken when the library was temporarily removed)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/8142668/225069620-6ddc7a73-260e-4b11-a525-9962d45cd893.png)

#### Actual
The request created by the ServiceWorked is pending consuming server resources (it ended up with 200 response even though it was canceled)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/8142668/225069799-9342ac01-4dd7-4be7-8b10-8dbc7264db13.png)

**Comment by guillaume-chervet** [comment]
Hi @Zamaletdinov , thank you very much for your issue.
It seem to be a bug from browsers: https://stackoverflow.com/questions/64198306/abort-controller-for-service-worker
Work seems in progress bug the bug is still active.

**Comment by Zamaletdinov** [comment]
Oh, that's something I didn't know before 😅 Thank you @guillaume-chervet!
